### ISSUE TITLE
Generate encodings.h as part of the build process

### ISSUE THREAD

**Issue by uckelman** [LightboxTech/liblightgrep#16]
encodings.h is generated from ICU. It would be nice if it could be generated as part of the build process, to ensure freshness.

Alas, here we crash into the reality of cross-compilation, as generating encodings.h during a MinGW cross-compile on Linux would require having a native build of the encodings.h generator already. This is one of the things which makes cross-compiling ICU itself so vexing. Avoid this path unless some inspiration strikes us, as there's no danger in encodings.h going stale---all that can happen is that we miss some names of _new_ encodings.

**Comment by jonstewart** [comment]
You created this issue even though we talked about it the other day and agreed it was silly. Totally mental.
